# Generated by Django 4.0.6 on 2023-05-25 02:12

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, default='', help_text='<small class="text-muted">CharField [1, 200]</small><hr><br>', max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(200)], verbose_name='ФИО(полностью)')),
                ('subdivision', models.CharField(blank=True, default='', help_text='<small class="text-muted">CharField [1, 50]</small><hr><br>', max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(50)], verbose_name='Подразделение')),
                ('position', models.CharField(blank=True, default='', help_text='<small class="text-muted">CharField [1, 200]</small><hr><br>', max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(200)], verbose_name='Профессия, должность')),
                ('phone', models.CharField(blank=True, default='', help_text='<small class="text-muted">CharField [1, 100]</small><hr><br>', max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)], verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, default='', help_text='<small class="text-muted">CharField [1, 300]</small><hr><br>', max_length=300, null=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(300)], verbose_name='Электронная почта(e-mail)')),
                ('title', models.CharField(blank=True, default='', help_text='<small class="text-muted">CharField [1, 300]</small><hr><br>', max_length=300, null=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(300)], verbose_name='Предложение(наименование)')),
                ('description', models.TextField(blank=True, default='', help_text='<small class="text-muted">CharField [1, 3000]</small><hr><br>', max_length=3000, null=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(3000)], verbose_name='Описание')),
                ('place', models.TextField(blank=True, default='', help_text='<small class="text-muted">CharField [1, 2000]</small><hr><br>', max_length=2000, null=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(2000)], verbose_name='Краткое описание объекта, место применения')),
                ('effect', models.TextField(blank=True, default='', help_text='<small class="text-muted">CharField [1, 1000]</small><hr><br>', max_length=1000, null=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(1000)], verbose_name='Ожидаемый эффект')),
                ('need', models.TextField(blank=True, default='', help_text='<small class="text-muted">CharField [1, 1000]</small><hr><br>', max_length=1000, null=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(1000)], verbose_name='Необходимые ТМЦ')),
                ('is_feedback', models.BooleanField(blank=True, default=False, help_text='<small class="text-muted">BooleanField</small><hr><br>', verbose_name='Нужно ли связаться с человеком')),
                ('link', models.TextField(blank=True, default='', help_text='<small class="text-muted">CharField [1, 900]</small><hr><br>', max_length=900, null=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(900)], verbose_name='Ссылка(на приложения)')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='<small class="text-muted">DateTimeField</small><hr><br>', null=True, verbose_name='Дата и время создания')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
                'db_table': 'django_app_post_model_table',
                'ordering': ('-created', 'title'),
            },
        ),
    ]
